version: "2.4"

services:

  dev:
    image: 16nsk/devcontainers:7.4-14
    command: sleep infinity
    volumes:
      - projects:/projects
    environment: 
      - MONGODB_CONNSTRING=mongodb://developer:developer@mongodb
    ports:
      - "${APP_PORT:-8000}:8000"
    # depends_on:
    #   - "mongo"

  mongo:
    image: mongo:4.4-rc-focal
    volumes:
      - mongo:/data
    restart: always
    ports:
      - 27017:27017
    # depends_on:
    #   - "mongo-express"
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: developer

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: developer
      ME_CONFIG_MONGODB_ADMINPASSWORD: developer
      ME_CONFIG_MONGODB_URL: mongodb://developer:developer@mongo:27017/

volumes:
  projects:
  mongo:

